# Generated by Django 5.2.15 on 2026-07-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_group_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pace_level',
            field=models.CharField(blank=True, choices=[('suave', 'Suave'), ('medio', 'Medio'), ('fuerte', 'Fuerte')], max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='target_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='target_elevation_gain_m',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
