# Generated by Django 5.2.15 on 2026-07-20 15:27, ampliada a mano con el backfill de
# estados (ver apps/events/CLAUDE.md, sección "Estados y ciclo de vida").

from django.db import migrations, models


def forwards_state_migration(apps, schema_editor):
    """Remapea los 5 estados antiguos a los 3 nuevos:
    - aceptado -> pendiente: "confirmado, aún no ha pasado" ya no existe como paso
      intermedio; el evento sigue pendiente hasta que un moderador lo marque realizado.
    - superado / cancelado -> archivado: ambos eran ya, en la práctica, "esto no sigue
      activo" (uno por dejadez, otro por cancelación explícita) — el modelo nuevo los
      funde en el único estado final que le corresponde a ambos.
    También archiva el chat_room de los que vienen de 'superado' (los de 'cancelado'
    ya lo estaban) para sostener la nueva invariante: archivado => chat en solo lectura.
    """
    Event = apps.get_model('events', 'Event')
    ChatRoom = apps.get_model('chat', 'ChatRoom')

    Event.objects.filter(state='aceptado').update(state='pendiente')
    Event.objects.filter(state__in=['superado', 'cancelado']).update(state='archivado')

    room_ids = list(
        Event.objects.filter(state='archivado', chat_room__isnull=False)
        .values_list('chat_room_id', flat=True)
    )
    ChatRoom.objects.filter(pk__in=room_ids, is_archived=False).update(is_archived=True)


def noop_reverse(apps, schema_editor):
    # Remapeo con pérdida de información (no se puede distinguir un 'archivado' que
    # venía de 'superado' de uno que venía de 'cancelado') — mismo criterio ya aplicado
    # en 0002_event_states_and_rsvp_rename.py para 'quizas'.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_pace_level_event_target_distance_km_and_more'),
        ('chat', '0002_chatroom_and_message_room'),  # ChatRoom.is_archived se añade aquí
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('realizado', 'Realizado'), ('archivado', 'Archivado')], default='pendiente', max_length=20),
        ),
        migrations.RunPython(forwards_state_migration, noop_reverse),
        migrations.RemoveField(
            model_name='event',
            name='is_archived',
        ),
    ]
