# Generated by Django 5.2.15 on 2026-06-15 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('gpx_file', models.FileField(upload_to='gpx/')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('elevation_gain_m', models.IntegerField(blank=True, null=True)),
                ('elevation_loss_m', models.IntegerField(blank=True, null=True)),
                ('max_elevation_m', models.IntegerField(blank=True, null=True)),
                ('min_elevation_m', models.IntegerField(blank=True, null=True)),
                ('track_geojson', models.JSONField(blank=True, null=True)),
                ('elevation_profile', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['author', '-created_at'], name='routes_rout_author__669c8a_idx')],
            },
        ),
    ]
