# Generated by Django 5.2.15 on 2026-07-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_and_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment_public_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('image', 'Imagen'), ('video', 'Vídeo')], max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
